### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#751]
It's happened quite a few times since I upgraded to Nougat on my Nexus 6P.

Example:
http://i.imgur.com/xBxpIAn.png

DSub doesn't have to be playing music for it to occur.

**Comment by daneren2005** [comment]
Can someone try out this apk and let me know if they see a brief toast `onPause` when they exit the application?  Pressing back or pressing home should both trigger it.

https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.1-fix.apk

**Comment by T7000** [comment]
"App not installed.
This package appears to be corrupt."

**Comment by daneren2005** [comment]
Weird.  I tried re-compiling it and uploading so try again.  I imagine something just got corrupted when either uploading to dropbox or you downloading it.

**Comment by daneren2005** [comment]
Another user screenshot: 
![screenshot_20161014-134552](https://cloud.githubusercontent.com/assets/414653/19457261/5d72dafe-947a-11e6-973d-e8be13bfcf7a.png)

**Comment by T7000** [comment]
Sorry it's not working

**Comment by keckelt** [comment]
Was able to install and saw the onPause toast when pressing back & pressing home on Android 6

**Comment by daneren2005** [comment]
Another user was able to install and verify that the onPause is still being called correctly on Android 7: `Just installed. I do see it when I exit by hitting back, by hitting home and when selecting exit from the daub home screen context menu. That last one it the only one that pauses the music though. I also see it a few other random times like entering the settings menu but that also doesn't pause music.`

**Comment by T7000** [comment]
Maybe I wasn't able because I'm enrolled in the beta?

**Comment by daneren2005** [comment]
It might be that simple.  Here are a couple of apk's based off the latest Beta code.  The first one upgrades the support library to the latest version made for Android 7.0.  The second one just removes casting functionality to see if something is going wrong with that.

https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.2%20BETA%20Upgrade%20Support%20Library.apk
https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.2%20BETA%20Remove%20Cast.apk

I am also looking into buying a a Nexus 5x to directly debug.  Can you think of any options you normally change which are different than the defaults?  While there are quite a few people reporting this, it definitely is not as high as it should be if everyone was experiencing this.  I'm trying to think of anything which could narrow down what the issue could be.

**Comment by T7000** [comment]
Don't tell me I gotta RMA T_T

http://i.imgur.com/yX14p1x.png

**Comment by daneren2005** [comment]
No they are not supposed to give toast messages. I just want to see if they still give you a huge battery drain while running them. And you can only have one installed at a time. Which one did you install and have you been noticing the same issue so far?

**Comment by khers** [comment]
The battery drain for me only shows up when DSub has to fetch something from the server to play.  If I am in offline mode or I play only cached music, battery usage is fine.  My hacky work around has been to cache what I want to hear and then force kill DSub, this seems to keep battery usage down quite a bit.  If you have something specific you want tested, please let me know (I have Nougat on a Nexus 6p).

**Comment by daneren2005** [comment]
I purchased a Nexus 5x, but didn't realize it only came with a USB C -> C cable.  I won't be able to do any more debugging on this for a couple more days until Amazon delivers some A -> C cables.

**Comment by pdf** [comment]
@daneren2005 should we be testing that 5.3.2 beta with DLNA removed?  I see the same battery drain on a Pixel running Nougat.

**Comment by daneren2005** [comment]
Yes that would be good. I bought a nexus 5x but am unable to reproduce the battery drain. Is anyone able to list their settings so I can see what I might need to set differently?

**Comment by pdf** [comment]
I get 'The package appears to be corrupt.'  I tried downloading the file from my computer too, to be sure, same thing.

There's no settings export in DSub, is there?

**Comment by daneren2005** [comment]
I forgot I have done an update since I put that out so the versions don't match.  I will have to recompile them again.  No there is no export.  I will have to see how long it would take to make one

**Comment by daneren2005** [comment]
Here are some different test versions:
DLNA removed: https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.2%20Remove%20DLNA.apk
Chromecast removed: https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.2%20Remove%20Chromecast.apk
All casting removed: https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.2%20Remove%20Casting.apk

**Comment by QuillOmega0** [comment]
I found the same issue where dsub was using a proportionally high amount of battery%. I installed the All casting removed package and have thus far seen a marked improvement in battery usage. Before it was not unusual to see 15-20% usage for dsub, but thus far I haven't even seen it show up in the battery usage monitor since updating.

**Comment by pdf** [comment]
I've been using the DLNA removed version the last couple of days, seems good but I want to give it a little more time.

**Comment by OpenAai** [comment]
I've been experiencing the same battery drain since I'm on Android 7, and also Android 7.1.1 on my Nexus 6P. The test version without any casting seems to be fine, no battery drain so far.
For the record. On one day battery usage for Dsub could be 20%, without actually using it, and the main usage of the app would be the Wifi connection.
Now, after using Dsub listening to music for an hour it's only on 1% of battery usage.

**Comment by pdf** [comment]
`DLNA removed` version seems to do the job here.

**Comment by daneren2005** [comment]
It's good to know the root issue is with DLNA.  I am trying to figure out what the root issue is

**Comment by OpenAai** [comment]
5.3.3 Is a battery drainer as wel.

**Comment by plastikman** [comment]
Since I have the same issues with the current release, I will install the non cast version and report.

**Comment by plastikman** [comment]
I can confirm that running with "DSub 5.3.2 Remove DLNA.apk" the battery drain is gone.  My phone is no longer smoking hot and the battery is back to respectable times!  

I know that the issue is not "Fixed" but I am glad my favorite music streamer is working properly again.  

Thanks @daneren2005

**Comment by QuillOmega0** [comment]
5.3.3 is still sucking the battery dry.

**Comment by plastikman** [comment]
@QuillOmega0 I don't think that @daneren2005 ever said that 5.3.3 was fixed.  Turn off auto updates in the play store for dsub, then install one of the known working versions that are listed in this issue.  I am sure once there is a workable update to solve the drain issues there will be a 5.3.4 release.

**Comment by daneren2005** [comment]
I'm sorry I have been out of town all week. I still don't have a solution but I am going to add a toggle to turn off DLNA for those with these issues as soon as I get back.

**Comment by daneren2005** [comment]
If anyone can try this out: https://dl.dropboxusercontent.com/u/23354647/DSub%205.3.3%20DNLA%20setting.apk.  There is a new setting under Settings -> Cast to turn off DLNA casting.  It should fix the battery drain issue people are seeing.  If it is I will probably add as part of the update to turn it off by default for everyone on Android 7.

**Comment by OpenAai** [comment]
Thanks Scott. I have just installed it, and will let you know.

**Comment by OpenAai** [comment]
The toggle works great!

**Comment by plastikman** [comment]
The toggle has solved the issue for me too.  Thanks for all the hard work.

**Comment by pdf** [comment]
:+1: The toggle in 5.3.4 appears to work around the problem here too, thanks.

**Comment by scienex** [comment]
so in order to breathe some life into this conversation again, here's my contribution...

i've been a happy dsub user for years now, but after recently installing it on my brand new samsung galaxy s10+ (running android pie and samsung's one ui) i've been dealing with a battery drain issue as well

it's not as dramatic as some previous examples shown in this thread, but i think you'll agree that _this_ is not as it should be:

![Screenshot_20190311-151603_Device care](https://user-images.githubusercontent.com/11860069/54132295-4342d980-4414-11e9-93d6-2ab2e91fb1bb.jpg)

(i don't remember dsub taking such large bites out of my battery capacity when i was using it on my pixel 2 xl)

i'm aware of the fact that this is probably a different issue (i toggled dlna casting off just to be sure), but i didn't want to add a new one only to be referred here ;)
if i should open this as a new issue, please let me know

**Comment by bjhiltbrand** [comment]
I was having really bad battery drain issues since upgrading to Android 10 as well. However, I toggled casting off and it fixed my battery drain issues. I toggled it back on and it started draining again. I don't know, it seems like it's still a problem somehow.

**Comment by jef** [comment]
Having draining problems as well. I haven't even used it today and it's used 14% of my battery.

- Pixel 4
- Android 10

**Comment by awsms** [comment]
> Update 1: Turned off DLNA and Syncing (it was syncing every hour). Will report back later to see what the usage is.
> 
> Update 2: Wow... A lot better battery performance. Not sure if it's related to sync or DLNA.

https://github.com/daneren2005/Subsonic/issues/976
Yup it was
